### ISSUE TITLE
Unpack .egg files

### ISSUE THREAD

**Issue by wangtz19** [network-traffic/AppSniffer#2]
Thank you for your excellent work. However, I am encountering issues unpacking the `.egg` format pcap datasets you shared on Google Drive. Despite my efforts, I could not find a valid tool to extract these files on Linux. I also attempted to install the ALZip program on a Windows 10 machine, but the installation failed without providing any explicit error messages.

Could you kindly recommend a suitable tool for unpacking `.egg` files, or consider re-uploading the datasets in more commonly used formats, such as `.zip` or `.tar`? Thank you for your time and assistance!

**Comment by sanghakoh** [comment]
Thank you for the comments. I hadn’t considered this issue. I re-upload the .zip file version, and let you know once they are uploaded.

**Comment by sanghakoh** [comment]
I've re-uploaded the .zip files. Please check the GitHub repository again and let me know if there are any other issues.

https://drive.google.com/drive/folders/1GFpV_6Ho14SUFVZX_a6YLVz6A0GwL2YO?usp=sharing

**Comment by wangtz19** [comment]
Thank you very much for your support!
